# ADMIN USERS (asumiendo que role_id = 1 corresponde a un rol administrador)

insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (1, 'Daiana', 'Videla', 'dvidela@somosmas.org', '$2a$10$Bz9kmnLhJb.xWc78LNymcugT0//TZRzNedtXgnfMWyYPVwuBcNlIG', 'IMAGE_URL', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (2, 'David', 'Sanchez', 'dsanchez@somosmas.org', '$2a$10$HBpQCfnYrfM/fknX0SP6E.SL3EKugWwZl1dRKvojFyl9in1LT8xDq', 'IMAGE_URL', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (3, 'Javier', 'Santillan', 'jsantillan@somosmas.org', '$2a$10$rTofGolmmPbys7Sv92e3nuQbwhqeOmxub6Kt2TVpJGtfsn20AIVCC', 'IMAGE_URL', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (4, 'Joel', 'Rodriguez', 'jrodriguez@somosmas.org', '$2a$10$dffyKLRJA8sI6OZbvrF5oukahCPWPXHPqWcXto9CARJFG8bvVKV/2', 'IMAGE_URL', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (5, 'Jonathan', 'Manera', 'jmanera@somosmas.org', '$2a$10$QU6xAhk./UtLtFpWIV4OauFkJXz0kzPvUZ6RWRV3ayYpI5./9aswu', 'IMAGE_URL', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (6, 'Matias', 'Romero', 'mromero@somosmas.org', '$2a$10$F68OaLbjl6BNZwiFwey55.fcmPh9xCbl4ek06rp/3TzVdbqZNVr9G', 'IMAGE_URL', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (7, 'Nicolas', 'Brandariz', 'nbrandariz@somosmas.org', '$2a$10$bW8l5mh9TqPV7wDOAYEDn.m6YyxKVXknMCWE2FJo7aaYTS24w1U4K', 'IMAGE_URL', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (8, 'Nicole', 'Rappoport', 'nrappoport@somosmas.org', '$2a$10$qTAyD7or9RmIxTP5OkqXs.j.cUPEMJbNU/NB8iISb63Clg4ydiTDy', 'IMAGE_URL', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (9, 'Sabrina', 'Incinga', 'sincinga@somosmas.org', '$2a$10$Ua7fNXynb3s4W/BXYdkJkOfv6lhFf5RfdYB0dZBQeFP8KS5vjiBSi', 'IMAGE_URL', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (10, 'Santiago', 'Pulido', 'spulido@somosmas.org', '$2a$10$YDxEl/3P0SQ9dza2XG3GVuTpMedRKE/FDakBlm//H/25ZqT9iYPtK', 'IMAGE_URL', 1, true, current_timestamp());

# REGULAR USERS (asumiendo que role_id = 2 corresponde a un rol de usuario regular)

insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (11, 'Ignacio', 'Casas', 'icasas@somosmas.org', '$2a$10$npmFpCbBFdtXjGGhgc1ste1quwGaF4MvkgYk9N2rBDFkOrV5Lj6M6', 'IMAGE_URL', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (12, 'Silvia', 'Cortes', 'scortes@somosmas.org', '$2a$10$583drnk4nz.pEZVUGFzsFufYa.6.U7MT531XT6VE7DYz5wF0.oU5K', 'IMAGE_URL', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (13, 'Marina', 'Sanabria', 'msanabria@somosmas.org', '$2a$10$P6IJfoAFcXhIdB4e3lj2q.b7xIrlOSwBre1pft.XMZnH0NEXt.ECC', 'IMAGE_URL', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (14, 'Berta', 'Cordoba', 'bcordoba@somosmas.org', '$2a$10$HGQUrES5DLbsGmhMPYrTpersz9DaoONY7MhUOCQHj9bfBOVUmYXZ.', 'IMAGE_URL', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (15, 'Antonio', 'Aranda', 'aaranda@somosmas.org', '$2a$10$kfei8555TtR3993R5VtE6.lf5p0akEa5z6tKiaw7KnS4B1LgH6Kni', 'IMAGE_URL', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (16, 'Carlota', 'Ceballos', 'cceballos@somosmas.org', '$2a$10$uFtwEua2ByAVW2joUedUGudtFUDYH2Cp6H/Wr0e/mt58W.pWMtWWy', 'IMAGE_URL', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (17, 'Anna', 'Villareal', 'avillareal@somosmas.org', '$2a$10$1lFQctDY/eQRNCiEjFvmc.YHqnFmMe0.rjCnLzSQ5f.IxVwcJhhxm', 'IMAGE_URL', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (18, 'Carmen', 'Lorente', 'clorente@somosmas.org', '$2a$10$PQm0XhQGcEHc0nZGjhM5Du21F6QwJ6lcvCba.hrPcrPyQxYTpPJ8i', 'IMAGE_URL', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (19, 'Beatriz', 'Valdez', 'bvaldez@somosmas.org', '$2a$10$qpEpaaKO.evVfC1AJBhpOevdfS92YqmIZN8ZC2ObqsXfJkxMcFX3C', 'IMAGE_URL', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (20, 'Diego', 'Pabon', 'dpabon@somosmas.org', '$2a$10$sGPpxqYyFMUWvV3A.0xEUendU18.NgApQjFvGgNkjoddgy7JywndC', 'IMAGE_URL', 2, true, current_timestamp());
