# ADMIN USERS (asumiendo que role_id = 1 corresponde a un rol administrador)

insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (1, 'Daiana', 'Videla', 'dvidela@somosmas.org', '$2a$10$xYuL3eZVJpDTTRUg29MGbe6G4gxSgFwPsckzzXHC9Y71znJUfQJGa', 'https://static-url.com/avatar.jpg', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (2, 'David', 'Sanchez', 'dsanchez@somosmas.org', '$2a$10$HBpQCfnYrfM/fknX0SP6E.SL3EKugWwZl1dRKvojFyl9in1LT8xDq', 'https://static-url.com/avatar.jpg', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (3, 'Javier', 'Santillan', 'jsantillan@somosmas.org', '$2a$10$rTofGolmmPbys7Sv92e3nuQbwhqeOmxub6Kt2TVpJGtfsn20AIVCC', 'https://static-url.com/avatar.jpg', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (4, 'Joel', 'Rodriguez', 'jrodriguez@somosmas.org', '$2a$10$dffyKLRJA8sI6OZbvrF5oukahCPWPXHPqWcXto9CARJFG8bvVKV/2', 'https://static-url.com/avatar.jpg', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (5, 'Jonathan', 'Manera', 'jmanera@somosmas.org', '$2a$10$Cbdo4nUjO68/chNxb00SpON.0i3.tjw/Hta4eNsKfQ.kBwao7r.O.', 'https://static-url.com/avatar.jpg', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (6, 'Matias', 'Romero', 'mromero@somosmas.org', '$2a$10$TUkYgI6ueUzU2xHW8ESI3edH7NfmZaovpg7ufRhQdqxVuO8YsDBWm', 'https://static-url.com/avatar.jpg', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (7, 'Nicolas', 'Brandariz', 'nbrandariz@somosmas.org', '$2a$10$bW8l5mh9TqPV7wDOAYEDn.m6YyxKVXknMCWE2FJo7aaYTS24w1U4K', 'https://static-url.com/avatar.jpg', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (8, 'Nicole', 'Rappoport', 'nrappoport@somosmas.org', '$2a$10$qTAyD7or9RmIxTP5OkqXs.j.cUPEMJbNU/NB8iISb63Clg4ydiTDy', 'https://static-url.com/avatar.jpg', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (9, 'Sabrina', 'Incinga', 'sincinga@somosmas.org', '$2a$10$Ua7fNXynb3s4W/BXYdkJkOfv6lhFf5RfdYB0dZBQeFP8KS5vjiBSi', 'https://static-url.com/avatar.jpg', 1, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (10, 'Santiago', 'Pulido', 'spulido@somosmas.org', '$2a$10$iXFt1SddmbR1FviZ7Q/SK.25Rh97PL2sbfpreZNMbv5KWKD4OIgBa', 'https://static-url.com/avatar.jpg', 1, true, current_timestamp());

# REGULAR USERS (asumiendo que role_id = 2 corresponde a un rol de usuario regular)

insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (11, 'Ignacio', 'Casas', 'icasas@somosmas.org', '$2a$10$ITT48.5FFWGdZBmD2JyWHe5H0hOsj4d/sfDmdQv7AUcKT9uOxbx1G', 'https://static-url.com/avatar.jpg', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (12, 'Silvia', 'Cortes', 'scortes@somosmas.org', '$2a$10$M.augnOmg0n6.fwjqflkie5YciqyYLaZnBWVyVRo5RG31ij/f9koO', 'https://static-url.com/avatar.jpg', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (13, 'Marina', 'Sanabria', 'msanabria@somosmas.org', '$2a$10$P6IJfoAFcXhIdB4e3lj2q.b7xIrlOSwBre1pft.XMZnH0NEXt.ECC', 'https://static-url.com/avatar.jpg', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (14, 'Berta', 'Cordoba', 'bcordoba@somosmas.org', '$2a$10$HGQUrES5DLbsGmhMPYrTpersz9DaoONY7MhUOCQHj9bfBOVUmYXZ.', 'https://static-url.com/avatar.jpg', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (15, 'Antonio', 'Aranda', 'aaranda@somosmas.org', '$2a$10$hmkACS5WBhZLJ9Q427fZLePo5/7obnhKMFZL9q6/GNaeDTZN/cPS6', 'https://static-url.com/avatar.jpg', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (16, 'Carlota', 'Ceballos', 'cceballos@somosmas.org', '$2a$10$uFtwEua2ByAVW2joUedUGudtFUDYH2Cp6H/Wr0e/mt58W.pWMtWWy', 'https://static-url.com/avatar.jpg', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (17, 'Anna', 'Villareal', 'avillareal@somosmas.org', '$2a$10$1lFQctDY/eQRNCiEjFvmc.YHqnFmMe0.rjCnLzSQ5f.IxVwcJhhxm', 'https://static-url.com/avatar.jpg', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (18, 'Carmen', 'Lorente', 'clorente@somosmas.org', '$2a$10$PQm0XhQGcEHc0nZGjhM5Du21F6QwJ6lcvCba.hrPcrPyQxYTpPJ8i', 'https://static-url.com/avatar.jpg', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (19, 'Beatriz', 'Valdez', 'bvaldez@somosmas.org', '$2a$10$UQBIjyikDdZ1Q4G7S./bcO3FcPsa/OI9WScb6mXyVLj.i/NGML4DC', 'https://static-url.com/avatar.jpg', 2, true, current_timestamp());
insert into user (user_id, first_name, last_name, email, password, photo, role_id, is_active, created_at) values (20, 'Diego', 'Pabon', 'dpabon@somosmas.org', '$2a$10$lJZIHAFXRVs6o5ty2rd44OTop3vPqCQhNZ5CKrXi/ONYd0YyKQHxu', 'https://static-url.com/avatar.jpg', 2, true, current_timestamp());
